In [ ]:
import requests
url = "https://raw.githubusercontent.com/Western-OC2-Lab/Student-Performance-and-Engagement-Prediction-eLearning-datasets/main/Student%20Performance%20Prediction-Binary%20Scenario/Student%20Performance%20Prediction-Binary.csv"

resp = requests.get(url)
resp.raise_for_status()

resp

In [3]:
import pandas as pd

In [4]:
from io import StringIO
data = StringIO(resp.text)

df = pd.read_csv(data)

df.head()

,Student ID,Quiz01 [10],Assignment01 [8],Midterm Exam [20],Assignment02 [12],Assignment03 [25],Final Exam [35],Course Grade,Total [100],Class
0,student000000,95,91,70,90,84,64,85,85,G
1,student000001,85,76,65,61,73,64,76,76,G
2,student000002,85,41,73,61,73,61,73,73,G
3,student000003,80,78,80,79,79,57,80,79,G
4,student000004,85,91,78,80,84,67,85,85,G

In [5]:
df.shape

(486, 10)

In [6]:
df.columns

Index(['Student ID', 'Quiz01 [10]', 'Assignment01 [8]', 'Midterm Exam [20]',
       'Assignment02 [12]', 'Assignment03 [25]', 'Final Exam [35]',
       'Course Grade', 'Total [100]', 'Class'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 486 entries, 0 to 485
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Student ID         486 non-null    object
 1   Quiz01 [10]        486 non-null    int64
 2   Assignment01 [8]   486 non-null    int64
 3   Midterm Exam [20]  486 non-null    int64
 4   Assignment02 [12]  486 non-null    int64
 5   Assignment03 [25]  486 non-null    int64
 6   Final Exam [35]    486 non-null    int64
 7   Course Grade       486 non-null    int64
 8   Total [100]        486 non-null    int64
 9   Class              486 non-null    object
dtypes: int64(8), object(2)
memory usage: 38.1+ KB

In [8]:
df.describe()

,Quiz01 [10],Assignment01 [8],Midterm Exam [20],Assignment02 [12],Assignment03 [25],Final Exam [35],Course Grade,Total [100]
count,486.000000,486.000000,486.000000,486.000000,486.000000,486.000000,486.000000,486.000000
mean,77.901235,75.479424,77.109053,77.133745,80.870370,62.181070,80.382716,80.487654
std,13.683406,17.733496,11.987383,15.179633,12.986498,14.938642,11.267032,11.282449
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,15.000000,15.000000
25%,70.000000,68.250000,70.000000,72.000000,77.000000,53.000000,75.000000,75.000000
50%,80.000000,79.000000,80.000000,81.000000,83.000000,64.000000,83.000000,83.000000
75%,85.000000,87.000000,85.000000,87.000000,89.000000,73.000000,88.000000,88.000000
max,100.000000,99.000000,98.000000,97.000000,100.000000,93.000000,100.000000,102.000000

In [9]:
df.isnull().sum()

Student ID           0
Quiz01 [10]          0
Assignment01 [8]     0
Midterm Exam [20]    0
Assignment02 [12]    0
Assignment03 [25]    0
Final Exam [35]      0
Course Grade         0
Total [100]          0
Class                0
dtype: int64

In [10]:
df['Class'].value_counts()

Class
G    465
W     21
Name: count, dtype: int64

In [15]:
import sqlite3

query = "CREATE TABLE test2(a VARCHAR(20) , b VARCHAR(20), c REAL, d INTEGER)"
con = con = sqlite3.connect("mydata.sqlite")
con.execute(query)

In [16]:
con.commit()

In [22]:
import numpy as np
float_data = pd.Series([1.2, -3.5, np.nan, 0])

In [13]:
float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [14]:
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool